### ISSUE TITLE
Setting Page Height

### ISSUE THREAD

**Issue by rullyrmd** [torresmateo/RawPrinterConsole#1]
Hi @torresmateo,

is possible to setting page height per-print?
in case I want to print A4/4

thanks

**Comment by torresmateo** [comment]
Hi @rullyrmd , it’s not possible to set dimensions, as the program receives a string as a parameter, depending on the printer’s configuration (size of characters, supported fonts, etc) you will get different widths and heights. It is a bit of trial and error. This program was used to fill pre-printed form though, so I know for a fact that given the right string it will print correctly on an A4 paper.

**Comment by rullyrmd** [comment]
Thank you! @torresmateo
